// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBToSC8BjCGYsXpzcVg7rMGlyHwZtL9748',
    appId: '1:825120093763:web:7f46d9b92d8090f71886f6',
    messagingSenderId: '825120093763',
    projectId: 'labfinal-fa21-bcs-130',
    authDomain: 'labfinal-fa21-bcs-130.firebaseapp.com',
    storageBucket: 'labfinal-fa21-bcs-130.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19db6CizuK2drDqu6qEDYfXGMYHsneko',
    appId: '1:825120093763:android:74a812a8f263b4391886f6',
    messagingSenderId: '825120093763',
    projectId: 'labfinal-fa21-bcs-130',
    storageBucket: 'labfinal-fa21-bcs-130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVtYgdwoMjr8pJX7PZth-q4R0UPJlJfU',
    appId: '1:825120093763:ios:b008588348320f741886f6',
    messagingSenderId: '825120093763',
    projectId: 'labfinal-fa21-bcs-130',
    storageBucket: 'labfinal-fa21-bcs-130.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVtYgdwoMjr8pJX7PZth-q4R0UPJlJfU',
    appId: '1:825120093763:ios:b008588348320f741886f6',
    messagingSenderId: '825120093763',
    projectId: 'labfinal-fa21-bcs-130',
    storageBucket: 'labfinal-fa21-bcs-130.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBToSC8BjCGYsXpzcVg7rMGlyHwZtL9748',
    appId: '1:825120093763:web:e4889c1fdf243f841886f6',
    messagingSenderId: '825120093763',
    projectId: 'labfinal-fa21-bcs-130',
    authDomain: 'labfinal-fa21-bcs-130.firebaseapp.com',
    storageBucket: 'labfinal-fa21-bcs-130.firebasestorage.app',
  );
}
